version: '3'
services:
  web:
    build: .
    volumes:
     - .:/code
    ports:
     - "${HIDDEN_TEMP_PORT}:5000"
    env_file:
     - ./host-env
    environment:
     - MY_HOST_IP=192.168.120.52
  redis:
    image: "${HIDDEN_REDIS_IMAGE_NAME}"
