# 
# https://docs.docker.com/compose/compose-file/
#

# docker-compose 버전 설정
version: "3"

# service 설정
services:
  web:
    # 이미지 설정
    image: hcvkb:latest

    # 배포 설정
    deploy:
      # global : 모든 docker host에 1개씩 배치
      # replicas : 설정한 갯수만큼 알아서 배치 (디폴트)
      replicas: 3
      #mode: global           
     
      resources:
        # 리소스 제한 설정
        limits:
          cpus: "1"
          memory: 1024M

      # lice-cycle 관리 정책 설정
      restart_policy:
        condition: on-failure   # 컨테이너 실패 시 즉시 다시 시작
    ports:
      - "8443:8443"
    networks:
      - webnet

# 네트워크 설정
networks:
  # webnet : 기본설정 (오버레이 네트워크 구성 & 라운드로빈 로드밸런싱)
  webnet:
