version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: hcvkb:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      restart_policy:
        # on-failure : 컨테이너 실패 시 즉시 다시 시작
        condition: on-failure
    ports:
      - "8443:8443"
    networks:
      - webnet
networks:
  # webnet : 기본설정 (오버레이 네트워크 구성 & 라운드로빈 로드밸런싱)
  webnet:
